name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # You might want to adjust this

      - name: Build for Linux amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o recterm-linux-amd64 main.go

      - name: Build for Linux arm64
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -o recterm-linux-arm64 main.go

      - name: Build for Windows amd64
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o recterm-windows-amd64.exe main.go

      - name: Build for Windows arm64
        env:
          GOOS: windows
          GOARCH: arm64
        run: go build -o recterm-windows-arm64.exe main.go

      - name: Build for macOS amd64
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o recterm-darwin-amd64 main.go

      - name: Build for macOS arm64
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o recterm-darwin-arm64 main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: true

      - name: Upload Linux amd64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-linux-amd64
          asset_name: recterm-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Linux arm64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-linux-arm64
          asset_name: recterm-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload Windows amd64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-windows-amd64.exe
          asset_name: recterm-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Windows arm64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-windows-arm64.exe
          asset_name: recterm-windows-arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS amd64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-darwin-amd64
          asset_name: recterm-darwin-amd64
          asset_content_type: application/octet-stream

      - name: Upload macOS arm64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: recterm-darwin-arm64
          asset_name: recterm-darwin-arm64
          asset_content_type: application/octet-stream
